# Generated by Django 5.1 on 2024-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="receiver_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
