# Generated by Django 5.1 on 2024-09-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friendships", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={},
        ),
    ]
